### ISSUE TITLE
[1.11.2] NineTails/ProjectX Crash on Load

### ISSUE THREAD

**Issue by hextrace** [TeamMD5/NineTailLib#6]
**Minecraft:** 1.11.2
**Forge:** xxx.2366
**NTL:** 1.6.137
**PX2:** 2.1.16
**Crash Report:**  https://paste.ee/p/jXnOB

**Issue:**
Server and Client crashes on load with a message NoClassDefFoundError -> keri/projectx/tile/TileEntityXycroniumLight

**Details:**
Recently updated my modpack with the latest and greatest in Minecraft aesthetics and tried to load it up before shipping it out.  Unfortunately, NineTails is being a bit cranky over some Xycronium and stomping the rest of my modpack into submission.

**Comment by KitsuneAlex** [comment]
well god damnit XD dont know what's up with that, will definetly look into it asap!

**Comment by KitsuneAlex** [comment]
should be fixed in the latest release, if you still have the issue, report it again but try to find out how to reproduce it
